### ISSUE TITLE
Ressurection

### ISSUE THREAD

**Issue by filyp** [mikel2000/batify#32]
Hi, just out of curiosity, why did you stop maintaining it? Was there some technical block that would be too time consuming? 
Also how hard do you think it would be to resurrect it and what would need to be done?

**Comment by mikel2000** [comment]
Hi, I stopped because there were too many changes in the supported browsers, which broke the batify functionality. Additionally, there were only a few interested in using it. The main reason was for sure, that they had to fund their wallets themselves. Brave users could use the grants they earned when activating the wallet. 
It's hard to estimate the efforts, which are needed to make it usable again. But because of the mentioned reasons, I think it's not worth it.

**Comment by filyp** [comment]
It's sad to hear that :c
I'd be fine with funding my wallet, but if it repels most people, you're right that it may not be worth it.
